services:
  spark-build:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_2.12.18
    container_name: spark-health-build
    working_dir: /workspace/spark
    volumes:
      - .:/workspace
    command: sbt clean package



